export const cuisinesList: string[] = [
  "Punjabi Cuisine",
  "Mughlai Cuisine",
  "Awadhi Cuisine",
  "South Indian Cuisine",
  "Bengali Cuisine",
  "Maharashtrian Cuisine",
  "Rajasthani Cuisine",
  "Gujarati Cuisine",
  "Hyderabadi Cuisine",
  "Goan Cuisine",
  "Kashmiri Cuisine",
  "Bihari Cuisine",
  "Pani Puri / Golgappa",
  "Samosas",
  "Vada Pav",
  "Chaat",
  "Pav Bhaji",
  "Dosas",
  "Indo-Chinese Cuisine",
  "Italian Cuisine",
  "Mexican Cuisine",
  "Middle Eastern Cuisine",
  "American Cuisine",
  "Thai Cuisine",
  "Japanese Cuisine",
  "Continental Cuisine",
  "Indo-Mexican Fusion",
  "Indo-Italian Fusion",
  "Vegan Cuisine",
  "Gluten-Free Cuisine",
];
